/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'eventId' : bigint,
  'organizerName' : string,
  'organizerId' : Principal,
  'bookingStatus' : BookingStatus,
  'bookingDate' : Time,
  'guestId' : Principal,
}
export type BookingStatus = { 'requested' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Event {
  'id' : bigint,
  'eventStyle' : EventStyle,
  'owner' : Principal,
  'date' : Time,
  'createdAt' : Time,
  'contact_number' : string,
  'locationType' : LocationType,
  'numberOfGuests' : bigint,
  'eventType' : EventType,
}
export interface EventPhoto {
  'id' : bigint,
  'contentType' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'filename' : string,
  'uploadedAt' : Time,
}
export type EventStyle = { 'couple' : null } |
  { 'friends' : null } |
  { 'corporate' : null } |
  { 'family' : null };
export type EventType = { 'anniversary' : null } |
  { 'wedding' : null } |
  { 'birthday' : null } |
  { 'corporate' : null };
export type ExternalBlob = Uint8Array;
export type LocationType = { 'destination' : null } |
  { 'home' : null };
export interface OrganizerProfile {
  'userId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'experienceYears' : bigint,
  'pricingRange' : string,
  'companyName' : string,
  'contactNumber' : string,
  'totalReviews' : bigint,
  'availabilityStatus' : { 'busy' : null } |
    { 'available' : null },
  'portfolio_images' : Array<PortfolioImage>,
}
export interface PortfolioImage { 'filename' : string, 'uploaded_at' : Time }
export interface Review {
  'id' : bigint,
  'eventId' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'organizerId' : Principal,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'createdAt' : Time,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioImage' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[bigint, Principal], bigint>,
  'createEvent' : ActorMethod<
    [EventType, LocationType, bigint, EventStyle, string, Time],
    bigint
  >,
  'deleteEventPhoto' : ActorMethod<[bigint], boolean>,
  'deletePortfolioImage' : ActorMethod<[string], boolean>,
  'filterOrganizers' : ActorMethod<
    [EventType, LocationType, bigint, EventStyle],
    Array<OrganizerProfile>
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllOrganizers' : ActorMethod<[], Array<OrganizerProfile>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getBookingsForEvent' : ActorMethod<[bigint], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getEventBookings' : ActorMethod<[bigint], Array<Booking>>,
  'getEventPhotos' : ActorMethod<[], Array<EventPhoto>>,
  'getEventPortfolioImages' : ActorMethod<[bigint], Array<PortfolioImage>>,
  'getEventReviews' : ActorMethod<[bigint], Array<Review>>,
  'getFreeOrganizers' : ActorMethod<[bigint, bigint], Array<OrganizerProfile>>,
  'getGuestBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getGuestEvents' : ActorMethod<[Principal], Array<Event>>,
  'getOrganizer' : ActorMethod<[Principal], OrganizerProfile>,
  'getOrganizerBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getOrganizerPortfolioImages' : ActorMethod<
    [Principal],
    Array<PortfolioImage>
  >,
  'getOrganizerProfile' : ActorMethod<[], [] | [OrganizerProfile]>,
  'getOrganizerReviews' : ActorMethod<[Principal], Array<Review>>,
  'getPortfolioImages' : ActorMethod<[], Array<PortfolioImage>>,
  'getPublicEventPhotos' : ActorMethod<[Principal], Array<EventPhoto>>,
  'getReview' : ActorMethod<[bigint], Review>,
  'getReviewsForEvent' : ActorMethod<[bigint], Array<Review>>,
  'getReviewsForOrganizer' : ActorMethod<[Principal], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerGuest' : ActorMethod<[string, string], undefined>,
  'requestBooking' : ActorMethod<[bigint, Principal], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOrganizerProfile' : ActorMethod<[OrganizerProfile], undefined>,
  'submitReview' : ActorMethod<[Principal, bigint, string, bigint], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'uploadEventPhoto' : ActorMethod<[ExternalBlob, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];