/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventType = IDL.Variant({
  'anniversary' : IDL.Null,
  'wedding' : IDL.Null,
  'birthday' : IDL.Null,
  'corporate' : IDL.Null,
});
export const LocationType = IDL.Variant({
  'destination' : IDL.Null,
  'home' : IDL.Null,
});
export const EventStyle = IDL.Variant({
  'couple' : IDL.Null,
  'friends' : IDL.Null,
  'corporate' : IDL.Null,
  'family' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PortfolioImage = IDL.Record({
  'filename' : IDL.Text,
  'uploaded_at' : Time,
});
export const OrganizerProfile = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'pricingRange' : IDL.Text,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'totalReviews' : IDL.Nat,
  'availabilityStatus' : IDL.Variant({
    'busy' : IDL.Null,
    'available' : IDL.Null,
  }),
  'portfolio_images' : IDL.Vec(PortfolioImage),
});
export const BookingStatus = IDL.Variant({
  'requested' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'organizerName' : IDL.Text,
  'organizerId' : IDL.Principal,
  'bookingStatus' : BookingStatus,
  'bookingDate' : Time,
  'guestId' : IDL.Principal,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'eventStyle' : EventStyle,
  'owner' : IDL.Principal,
  'date' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'contact_number' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'locationType' : LocationType,
  'numberOfGuests' : IDL.Nat,
  'eventType' : EventType,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'organizerId' : IDL.Principal,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'createdAt' : Time,
  'role' : UserRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const EventPhoto = IDL.Record({
  'id' : IDL.Nat,
  'contentType' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'uploadedAt' : Time,
});
export const PaginatedBookings = IDL.Record({
  'bookings' : IDL.Vec(Booking),
  'totalCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPortfolioImage' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Nat], []),
  'createEvent' : IDL.Func(
      [
        EventType,
        LocationType,
        IDL.Nat,
        EventStyle,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteEventPhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePortfolioImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'filterOrganizers' : IDL.Func(
      [EventType, LocationType, IDL.Nat, EventStyle],
      [IDL.Vec(OrganizerProfile)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllOrganizers' : IDL.Func([], [IDL.Vec(OrganizerProfile)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByGuest' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsForEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getEventBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getEventPhotos' : IDL.Func([], [IDL.Vec(EventPhoto)], ['query']),
  'getEventPortfolioImages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PortfolioImage)],
      ['query'],
    ),
  'getEventReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getFreeOrganizers' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(OrganizerProfile)],
      ['query'],
    ),
  'getGuestBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getGuestBookingsForCaller' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getGuestEvents' : IDL.Func([IDL.Principal], [IDL.Vec(Event)], ['query']),
  'getOrganizer' : IDL.Func([IDL.Principal], [OrganizerProfile], ['query']),
  'getOrganizerBookings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getOrganizerBookingsForCaller' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getOrganizerBookingsPaginated' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [PaginatedBookings],
      ['query'],
    ),
  'getOrganizerPortfolioImages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PortfolioImage)],
      ['query'],
    ),
  'getOrganizerProfile' : IDL.Func([], [IDL.Opt(OrganizerProfile)], ['query']),
  'getOrganizerReviews' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getPortfolioImages' : IDL.Func([], [IDL.Vec(PortfolioImage)], ['query']),
  'getPublicEventPhotos' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EventPhoto)],
      ['query'],
    ),
  'getReview' : IDL.Func([IDL.Nat], [Review], ['query']),
  'getReviewsForEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getReviewsForOrganizer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerGuest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestBooking' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOrganizerProfile' : IDL.Func([OrganizerProfile], [], []),
  'submitReview' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        EventType,
        LocationType,
        IDL.Nat,
        EventStyle,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'uploadEventPhoto' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'anniversary' : IDL.Null,
    'wedding' : IDL.Null,
    'birthday' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const LocationType = IDL.Variant({
    'destination' : IDL.Null,
    'home' : IDL.Null,
  });
  const EventStyle = IDL.Variant({
    'couple' : IDL.Null,
    'friends' : IDL.Null,
    'corporate' : IDL.Null,
    'family' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PortfolioImage = IDL.Record({
    'filename' : IDL.Text,
    'uploaded_at' : Time,
  });
  const OrganizerProfile = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'pricingRange' : IDL.Text,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'totalReviews' : IDL.Nat,
    'availabilityStatus' : IDL.Variant({
      'busy' : IDL.Null,
      'available' : IDL.Null,
    }),
    'portfolio_images' : IDL.Vec(PortfolioImage),
  });
  const BookingStatus = IDL.Variant({
    'requested' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'organizerName' : IDL.Text,
    'organizerId' : IDL.Principal,
    'bookingStatus' : BookingStatus,
    'bookingDate' : Time,
    'guestId' : IDL.Principal,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'eventStyle' : EventStyle,
    'owner' : IDL.Principal,
    'date' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'contact_number' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'locationType' : LocationType,
    'numberOfGuests' : IDL.Nat,
    'eventType' : EventType,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'organizerId' : IDL.Principal,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'createdAt' : Time,
    'role' : UserRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const EventPhoto = IDL.Record({
    'id' : IDL.Nat,
    'contentType' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'uploadedAt' : Time,
  });
  const PaginatedBookings = IDL.Record({
    'bookings' : IDL.Vec(Booking),
    'totalCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPortfolioImage' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Nat], []),
    'createEvent' : IDL.Func(
        [
          EventType,
          LocationType,
          IDL.Nat,
          EventStyle,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteEventPhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePortfolioImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'filterOrganizers' : IDL.Func(
        [EventType, LocationType, IDL.Nat, EventStyle],
        [IDL.Vec(OrganizerProfile)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllOrganizers' : IDL.Func([], [IDL.Vec(OrganizerProfile)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByGuest' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsForEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getEventBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getEventPhotos' : IDL.Func([], [IDL.Vec(EventPhoto)], ['query']),
    'getEventPortfolioImages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PortfolioImage)],
        ['query'],
      ),
    'getEventReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getFreeOrganizers' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(OrganizerProfile)],
        ['query'],
      ),
    'getGuestBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getGuestBookingsForCaller' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getGuestEvents' : IDL.Func([IDL.Principal], [IDL.Vec(Event)], ['query']),
    'getOrganizer' : IDL.Func([IDL.Principal], [OrganizerProfile], ['query']),
    'getOrganizerBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getOrganizerBookingsForCaller' : IDL.Func(
        [],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getOrganizerBookingsPaginated' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [PaginatedBookings],
        ['query'],
      ),
    'getOrganizerPortfolioImages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PortfolioImage)],
        ['query'],
      ),
    'getOrganizerProfile' : IDL.Func(
        [],
        [IDL.Opt(OrganizerProfile)],
        ['query'],
      ),
    'getOrganizerReviews' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getPortfolioImages' : IDL.Func([], [IDL.Vec(PortfolioImage)], ['query']),
    'getPublicEventPhotos' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EventPhoto)],
        ['query'],
      ),
    'getReview' : IDL.Func([IDL.Nat], [Review], ['query']),
    'getReviewsForEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getReviewsForOrganizer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerGuest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestBooking' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOrganizerProfile' : IDL.Func([OrganizerProfile], [], []),
    'submitReview' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          EventType,
          LocationType,
          IDL.Nat,
          EventStyle,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'uploadEventPhoto' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };